Enabled oh-my-zsh
Signed-off-by: Steven Bayer <smbayer@amazon.com>

diff --git a/runcoms/zshrc b/runcoms/zshrc
--- a/runcoms/zshrc
+++ b/runcoms/zshrc
@@ -1,8 +1,8 @@
-# Amazon Q pre block. Keep at the top of this file.
-if [[ -f "${HOME}/.config/enable-amazon-q" ]]; then
-    if [[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh" ]]; then
-        builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh"
-    fi
+# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
+# Initialization code that may require console input (password prompts, [y/n]
+# confirmations, etc.) must go above this block; everything else may go below.
+if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
+  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
 fi
 
 # Debug toggle
@@ -15,7 +15,137 @@ if [[ "${ZSH_DEBUG}" == "true" ]]; then
     PS4='+%N:%i> '
 fi
 
-export ZPREZTO_HOME=${HOME}/.zprezto
+export ZSH_TMUX_AUTOSTART=false
+export ZSH_TMUX_AUTOSTART_ONCE=true
+export ZSH_TMUX_AUTONAME_SESSION=true
+export ZSH_TMUX_ITERM2=true
+export ZSH_TMUX_UNICODE=true
+export ZSH_TMUX_DETACHED=true
+
+# If you come from bash you might have to change your $PATH.
+# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
+
+# Path to your Oh My Zsh installation.
+export ZSH="$HOME/.oh-my-zsh"
+
+# Set name of the theme to load --- if set to "random", it will
+# load a random theme each time Oh My Zsh is loaded, in which case,
+# to know which specific one was loaded, run: echo $RANDOM_THEME
+# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
+# ZSH_THEME="headline"
+ZSH_THEME="powerlevel10k/powerlevel10k"
+
+# Set list of themes to pick from when loading at random
+# Setting this variable when ZSH_THEME=random will cause zsh to load
+# a theme from this variable instead of looking in $ZSH/themes/
+# If set to an empty array, this variable will have no effect.
+# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )
+
+# Uncomment the following line to use case-sensitive completion.
+# CASE_SENSITIVE="true"
+
+# Uncomment the following line to use hyphen-insensitive completion.
+# Case-sensitive completion must be off. _ and - will be interchangeable.
+# HYPHEN_INSENSITIVE="true"
+
+# Uncomment one of the following lines to change the auto-update behavior
+# zstyle ':omz:update' mode disabled  # disable automatic updates
+# zstyle ':omz:update' mode auto      # update automatically without asking
+# zstyle ':omz:update' mode reminder  # just remind me to update when it's time
+
+# Uncomment the following line to change how often to auto-update (in days).
+# zstyle ':omz:update' frequency 13
+
+# Uncomment the following line if pasting URLs and other text is messed up.
+# DISABLE_MAGIC_FUNCTIONS="true"
+
+# Uncomment the following line to disable colors in ls.
+# DISABLE_LS_COLORS="true"
+
+# Uncomment the following line to disable auto-setting terminal title.
+# DISABLE_AUTO_TITLE="true"
+
+# Uncomment the following line to enable command auto-correction.
+# ENABLE_CORRECTION="true"
+
+# Uncomment the following line to display red dots whilst waiting for completion.
+# You can also set it to another string to have that shown instead of the default red dots.
+# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
+# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
+# COMPLETION_WAITING_DOTS="true"
+
+# Uncomment the following line if you want to disable marking untracked files
+# under VCS as dirty. This makes repository status check for large repositories
+# much, much faster.
+# DISABLE_UNTRACKED_FILES_DIRTY="true"
+
+# Uncomment the following line if you want to change the command execution time
+# stamp shown in the history command output.
+# You can set one of the optional three formats:
+# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
+# or set a custom format using the strftime function format specifications,
+# see 'man strftime' for details.
+# HIST_STAMPS="mm/dd/yyyy"
+
+# Would you like to use another custom folder than $ZSH/custom?
+ZSH_CUSTOM="${HOME}/.zprezto/oh-my-zsh/custom"
+
+# Which plugins would you like to load?
+# Standard plugins can be found in $ZSH/plugins/
+# Custom plugins may be added to $ZSH_CUSTOM/plugins/
+# Example format: plugins=(rails git textmate ruby lighthouse)
+# Add wisely, as too many plugins slow down shell startup.
+plugins=(
+    git
+    iterm2
+    lol
+    magic-enter
+    man
+    pip
+    pylint
+    python
+    ssh
+    timer
+    # tmux
+    vscode
+    zoxide
+    zsh-autosuggestions
+    zsh-interactive-cd
+    zsh-syntax-highlighting
+)
+
+source "${ZSH}/oh-my-zsh.sh"
+
+# User configuration
+
+# export MANPATH="/usr/local/man:$MANPATH"
+
+# You may need to manually set your language environment
+# export LANG=en_US.UTF-8
+
+# Preferred editor for local and remote sessions
+# if [[ -n $SSH_CONNECTION ]]; then
+#   export EDITOR='vim'
+# else
+#   export EDITOR='nvim'
+# fi
+
+# Compilation flags
+# export ARCHFLAGS="-arch $(uname -m)"
+
+# Set personal aliases, overriding those provided by Oh My Zsh libs,
+# plugins, and themes. Aliases can be placed here, though Oh My Zsh
+# users are encouraged to define aliases within a top-level file in
+# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
+# - $ZSH_CUSTOM/aliases.zsh
+# - $ZSH_CUSTOM/macos.zsh
+# For a full list of active aliases, run `alias`.
+#
+# Example aliases
+# alias zshconfig="mate ~/.zshrc"
+# alias ohmyzsh="mate ~/.oh-my-zsh"
+
+export ZPREZTO_HOME="${HOME}/.zprezto"
 
 # Helper function to safely add paths
 function add_to_path() {
@@ -65,21 +195,18 @@ fi
 # Source configuration files
 source_if_exists "${HOME}/.zprezto/runcoms/amazonrc"
 source_if_exists "${HOME}/.fzf.zsh"
-source_if_exists "${HOME}/.iterm2_shell_integration.bash"
 source_if_exists "${HOME}/.iterm2_shell_integration.zsh"
-source_if_exists "${HOME}/.cargo/bin"
-source_if_exists "/usr/local/aws-cli/v2/current/bin"
 source_if_exists "${HOME}/.fzf.zsh"
-source_if_exists "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
+# source_if_exists "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
 
 
 export EDITOR=nvim
 export VISUAL=nvim
 
 
-if type starship > /dev/null; then
-    eval "$(starship init zsh)"
-fi
+# if type starship > /dev/null; then
+#     eval "$(starship init zsh)"
+# fi
 
 # Find latest java version
 if [[ -z $JAVA_HOME ]]; then
@@ -170,76 +297,221 @@ function tmux-tail () {
 alias "dc"="docker-compose"
 alias "rm-images"="docker images | awk 'NR!=1' | awk '{ print \$3 }' | xargs docker image rm"
 
-function docker-compose-restart () {
-    local WORKER="${1}"
-    echo "Restarting worker ${WORKER}"
-    docker-compose stop ${WORKER}
-    docker-compose build ${WORKER}
-    docker-compose up --no-start ${WORKER}
-    docker-compose start ${WORKER}
-}
-
-function nvm-init () {
-    export NVM_DIR="${HOME}/.nvm"
-
-    # Check if nvm is installed via homebrew
-    if [ -s "/opt/homebrew/opt/nvm/nvm.sh" ]; then
-        \. "/opt/homebrew/opt/nvm/nvm.sh"
-        [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
-    # Fallback to NVM_DIR if homebrew installation not found
-    elif [ -s "$NVM_DIR/nvm.sh" ]; then
-        \. "$NVM_DIR/nvm.sh"
-    else
-        echo "nvm not found. Please install nvm first."
-        return 1
-    fi
-
-    nvm current
-}
-
-function iterm-help () {
-    echo "DevDesktop:                    <󰘴-󰘳> a"
-    echo "Autocompletion:                <󰘳> ;"
-    echo "Toolbelt:                      <󰘶-󰘳> b"
-    echo "Edit Session:                  <󰘳> i"
-    echo "Timestamps:                    <󰘶-󰘳> e"
-    echo "Alert On Finish:               <󰘵-󰘳> a"
-    echo "Git History:                   <󰘳> g <󰘳> h"
-}
-
-function tmux-help () {
-    echo "Tmux Create Window:            <󰘴-b> c"
-    echo "Tmux Rename Window:            <󰘴-b> ,"
-    echo "Tmux Close Window:             <󰘴-b> &"
-    echo "Tmux List Window:              <󰘴-b> w"
-    echo "Tmux Previous Window:          <󰘴-b> p"
-    echo "Tmux Next Window:              <󰘴-b> n"
-    echo "Tmux Switch Window:            <󰘴-b> 0..9"
-    echo "Tmux Split Window Vertical:    <󰘴-b> %"
-    echo 'Tmux Split Window Horizontal:  <󰘴-b> "'
-    echo "Tmux Next Pane:                <󰘴-b> o"
-    echo "Tmux Show Pane Numbers:        <󰘴-b> p"
-    echo "Tmux Switch Pane:              <󰘴-b> q 0..9"
-    echo "Tmux Convert Pane To Window:   <󰘴-b> q 0..9"
-    echo "Tmux Close Pane:               <󰘴-b> x"
-}
-
-function lvim-help () {
-    echo "https://vimtricks.com/p/vim-code-folding/"
-    echo "za – Toggles the current fold open or closed. – The most useful command to know of all of these."
-    echo "zA – Same as za except it toggles all folds beneath as well. Since folds can be nested (such as with indent folding), this will toggle the state of all the folds underneath of it, not just the current fold."
-    echo "zc – Close the current fold."
-    echo "zC – Same as above, but closes folds nested underneath as well."
-    echo "zo – Open the current fold."
-    echo "zO – Same as above, but opens folds nested underneath as well."
-    echo "vimrc no fold: ':set nofoldenable'"
-    echo "<S-\`> - Open terminal"
-    echo "    or :terminal"
-}
-
-# Amazon Q post block. Keep at the bottom of this file.
-if [[ -f "${HOME}/.config/enable-amazon-q" ]]; then
-    if [[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh" ]]; then
-        builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh"
-    fi
+if [[ -s "/usr/local/aws-cli/v2/current/bin" ]]; then
+    autoload bashcompinit && bashcompinit
+    autoload -Uz compinit && compinit
+    complete -C '/usr/local/aws-cli/v2/current/bin' aws
+elif [[ -s "/usr/local/aws-cli" ]]; then
+    autoload bashcompinit && bashcompinit
+    autoload -Uz compinit && compinit
+    complete -C '/usr/local/aws-cli/bin' aws
 fi
+
+# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
+[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
+
+
+
+# Enable zsh debugging if toggle is on
+if [[ "${ZSH_DEBUG}" == "true" ]]; then
+    setopt XTRACE
+    setopt VERBOSE
+    PS4='+%N:%i> '
+fi
+
+# Helper function to safely source files
+function source_if_exists() {
+    local file="${1}"
+    local shell="${SHELL##*/}"
+    local source_file="${0}"
+    
+    # Skip if file doesn't exist
+    if [[ ! -s "${file}" ]]; then
+        [[ "${ZSH_DEBUG}" == "true" ]] && echo "[$(date '+%Y-%m-%d %H:%M:%S')] [${source_file}] File does not exist or is empty: ${file}"
+        return
+    fi
+    
+    # Handle shell-specific files
+    if [[ "${file}" == *.zsh ]]; then
+        [[ "${shell}" == "zsh" ]] && {
+            [[ "${ZSH_DEBUG}" == "true" ]] && echo "[$(date '+%Y-%m-%d %H:%M:%S')] [${source_file}] Sourcing zsh file: ${file}"
+            if ! (source "${file}"); then
+                [[ "${ZSH_DEBUG}" == "true" ]] && echo "[$(date '+%Y-%m-%d %H:%M:%S')] [${source_file}] Failed to source zsh file: ${file}"
+            fi
+        }
+    elif [[ "${file}" == *.bash ]]; then
+        [[ "${shell}" == "bash" ]] && {
+            [[ "${ZSH_DEBUG}" == "true" ]] && echo "[$(date '+%Y-%m-%d %H:%M:%S')] [${source_file}] Sourcing bash file: ${file}"
+            if ! (source "${file}"); then
+                [[ "${ZSH_DEBUG}" == "true" ]] && echo "[$(date '+%Y-%m-%d %H:%M:%S')] [${source_file}] Failed to source bash file: ${file}"
+            fi
+        }
+    else
+        # Source non-shell-specific files
+        [[ "${ZSH_DEBUG}" == "true" ]] && echo "[$(date '+%Y-%m-%d %H:%M:%S')] [${source_file}] Sourcing file: ${file}"
+        if ! (source "${file}"); then
+            [[ "${ZSH_DEBUG}" == "true" ]] && echo "[$(date '+%Y-%m-%d %H:%M:%S')] [${source_file}] Failed to source file: ${file}"
+        fi
+    fi
+}
+
+# Execute code that does not affect the current session in the background.
+{
+  # Compile the completion dump to increase startup speed.
+  zcompdump="${ZDOTDIR:-${HOME}}/.zcompdump"
+  if [[ -s "${zcompdump}" && (! -s "${zcompdump}.zwc" || "${zcompdump}" -nt "${zcompdump}.zwc") ]]; then
+    zcompile "${zcompdump}"
+  fi
+} &!
+
+# Print a random, hopefully interesting, adage.
+if (( $+commands[fortune] )); then
+  if [[ -t 0 || -t 1 ]]; then
+    fortune -s
+  fi
+fi
+
+# Source RVM if it exists
+# source_if_exists "${HOME}/.rvm/scripts/rvm"
+
+# ---- zoxide -----
+eval "$(zoxide init zsh)"
+alias cd='z'
+alias cdi='zi'
+
+# ---- FZF -----
+
+# --- setup fzf theme ---
+fg="#CBE0F0"
+bg="#011628"
+bg_highlight="#143652"
+purple="#B388FF"
+blue="#06BCE4"
+cyan="#2CF9ED"
+
+export FZF_DEFAULT_OPTS="--color=fg:${fg},bg:${bg},hl:${purple},fg+:${fg},bg+:${bg_highlight},hl+:${purple},info:${blue},prompt:${cyan},pointer:${cyan},marker:${cyan},spinner:${cyan},header:${cyan}"
+
+# -- Use fd instead of fzf --
+
+export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
+export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
+export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"
+
+# Use fd (https://github.com/sharkdp/fd) for listing path candidates.
+# - The first argument to the function ($1) is the base path to start traversal
+# - See the source code (completion.{bash,zsh}) for the details.
+function _fzf_compgen_path() {
+  fd --hidden --exclude .git . "${1}"
+}
+
+# Use fd to generate the list for directory completion
+function _fzf_compgen_dir() {
+  fd --type=d --hidden --exclude .git . "${1}"
+}
+
+# source_if_exists "${ZDOTDIR:-${HOME}}/.zprezto/fzf-git.sh"
+
+export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range :500 {}'"
+export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"
+
+# Advanced customization of fzf options via _fzf_comprun function
+# - The first argument to the function is the name of the command.
+# - You should make sure to pass the rest of the arguments to fzf.
+function _fzf_comprun() {
+  local command="${1}"
+  shift
+
+  case "${command}" in
+    cd)           fzf --preview 'eza --tree --color=always {} | head -200' "$@" ;;
+    export|unset) fzf --preview "eval 'echo \$'{}"         "$@" ;;
+    ssh)          fzf --preview 'dig {}'                   "$@" ;;
+    *)            fzf --preview "bat -n --color=always --line-range :500 {}" "$@" ;;
+  esac
+}
+
+function fzf-keybinds() {
+    echo "Files                         <󰘴> g <󰘴> F"
+    echo "Branches                      <󰘴> g <󰘴> B"
+    echo "Tags                          <󰘴> g <󰘴> T"
+    echo "Remotes                       <󰘴> g <󰘴> R"
+    echo "commit Hashes                 <󰘴> g <󰘴> H"
+    echo "Stashes                       <󰘴> g <󰘴> S"
+    echo "reflogs                       <󰘴> g <󰘴> L"
+    echo "Worktrees                     <󰘴> g <󰘴> W"
+    echo "Each ref (git for-each-ref)   <󰘴> g <󰘴> E"
+}
+
+# ----- Bat (better cat) -----
+
+if type "bat" > /dev/null; then
+    alias cat="bat -P"
+fi
+
+# ---- Eza (better ls) -----
+
+# --color-scale, --colour-scale
+#   highlight levels of field distinctly.  Use comma(,) separated list of all, age, size
+eza_cmd="eza --color=auto --long --git --icons=always --group-directories-first"
+alias ll="${eza_cmd} --color-scale-mode=fixed --time-style=relative --group-directories-first"
+alias la="${eza_cmd} --color-scale-mode=fixed --time-style=relative --group-directories-first --all"
+alias lt="${eza_cmd} --color-scale-mode=gradient --color-scale=age --no-time --tree --level 2"
+
+# ---- Jump -----
+
+[[ -s "${HOME}/.autojump/etc/profile.d/autojump.sh" ]] && source "${HOME}/.autojump/etc/profile.d/autojump.sh"
+autoload -U compinit && compinit -u
+
+# ---- atuin -----
+
+# ---- atuin (command history) -----
+if type "atuin" > /dev/null
+then
+    eval "$(atuin init zsh)"
+    # eval "$(atuin init zsh --disable-up-arrow)"
+    eval "$(atuin gen-completions --shell zsh)"
+fi
+
+test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
+
+# ---- pipx autocomplete -----
+# Maybe delete for Q?
+if type "pipx" > /dev/null && type "register-python-argcomplete" > /dev/null
+then
+    autoload -U compinit && compinit
+    # I might not need this:
+    # autoload -U bashcompinit
+    # bashcompinit
+    eval "$(register-python-argcomplete pipx)"
+fi
+
+if [ -d "$HOME/.pyenv" ]
+then
+    export PYENV_ROOT="$HOME/.pyenv"
+    [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
+    eval "$(pyenv init -)"
+fi
+
+function colorize() {
+    local message="$1"
+    local match_text="$2"
+    local color="$3"
+    local reset=$'\e[0m'
+    
+    # Escape special characters in match_text for sed
+    local escaped_match=$(echo "$match_text" | sed 's/[\/&]/\\&/g')
+    
+    # Use printf to properly interpret escape sequences
+    # The $'...' syntax in zsh allows for interpretation of escape sequences
+    printf "%b" "$(echo "$message" | sed -E "s/$escaped_match/$color&$reset/gI")"
+}
+
+function colorize_regex() {
+    local message="$1"
+    local pattern="$2"
+    local color="$3"
+    local reset=$'\e[0m'
+    
+    # Use printf to properly interpret escape sequences
+    # The -E flag enables extended regular expressions
+    printf "%b" "$(echo "$message" | sed -E "s/($pattern)/$color\\1$reset/g")"
+}
